### PR TITLE
Open git-bash.exe in current active file path (v1.1.0)

### PR DESCRIPTION
**Pull request by leotm**
Equivalent to:
* GitHub Desktop: _Open in Git Shell_
* Git for Windows: _Git Bash Here_.

### CODE REVIEW

**Comment by Robert923** [comment]
Hah!   I was working on adding your suggestion as well.
I think in src/extension.ts line 24 there's a possibility to crash if there's no open file.
Also, the new version I just pushed will still fall-back to the workspace root if there's no open file.

I did use your path code though to get the directory and I've published the new version.

Thanks @leotm!

**Comment by Robert923** [comment]
Implemented

**Comment by leotm** [comment]
Ahh you got me 🙌 well spotted.
Tested and lookin' good.
Appreciate the mention!

**Comment by leotm** [comment]
Also requested https://github.com/Microsoft/vscode/issues/15991 may be a while😴

**Pull request closed without merging**
